version: "1"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "9000:9000"
    links:
      - psql 
  psql: 
    container_name: psql
    image: postgres:14.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=tommy
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=psql
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
