// App state
export const APP_INIT = 'APP_INIT';
export const APP_RESET = 'APP_RESET';
export const APP_BASE_URL = 'APP_BASE_URL';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const SET_ERRORS = 'SET_ERRORS';

// alerts
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// Editorials
export const GET_TEAM_MEMBERS_SUBMIT = 'GET_TEAM_MEMBERS_SUBMIT';
export const GET_TEAM_MEMBERS_SUCCESS = 'GET_TEAM_MEMBERS_SUCCESS';
export const GET_TEAM_MEMBERS_ERROR = 'GET_TEAM_MEMBERS_ERROR';

export const UPDATE_TEAM_MEMBER_SUBMIT = 'UPDATE_TEAM_MEMBER_SUBMIT';
export const UPDATE_TEAM_MEMBER_SUCCESS = 'UPDATE_TEAM_MEMBER_SUCCESS';
export const UPDATE_TEAM_MEMBER_ERROR = 'UPDATE_TEAM_MEMBER_ERROR';

export const DELETE_TEAM_MEMBER_SUBMIT = 'DELETE_TEAM_MEMBER_SUBMIT';
export const DELETE_TEAM_MEMBER_SUCCESS = 'DELETE_TEAM_MEMBER_SUCCESS';
export const DELETE_TEAM_MEMBER_ERROR = 'DELETE_TEAM_MEMBER_ERROR';

export const UPLOAD_TEAM_MEMBER_IMAGE_SUBMIT = 'UPLOAD_TEAM_MEMBER_IMAGE_SUBMIT';
export const UPLOAD_TEAM_MEMBER_IMAGE_SUCCESS = 'UPLOAD_TEAM_MEMBER_IMAGE_SUCCESS';
export const UPLOAD_TEAM_MEMBER_IMAGE_ERROR = 'UPLOAD_TEAM_MEMBER_IMAGE_ERROR';

export const TEAM_MEMBER_UPLOAD_IMAGE_SET = 'TEAM_MEMBER_UPLOAD_IMAGE_SET';
export const TEAM_MEMBER_UPLOAD_IMAGE_CLEAR = 'TEAM_MEMBER_UPLOAD_IMAGE_CLEAR';

export const EDIT_TEAM_MEMBER = 'EDIT_TEAM_MEMBER';
export const EDIT_TEAM_MEMBER_LIST = 'EDIT_TEAM_MEMBER_LIST';
export const EDIT_TEAM_MEMBER_DROPDOWNS = 'EDIT_TEAM_MEMBER_DROPDOWNS';

export const SET_SELECTED_TEAM_MEMBER = 'SET_SELECTED_TEAM_MEMBER';
export const CLEAR_SELECTED_TEAM_MEMBER = 'CLEAR_SELECTED_TEAM_MEMBER';

export const SET_NEW_TEAM_MEMBER = 'SET_NEW_TEAM_MEMBER';
