// App state
export const APP_INIT = 'APP_INIT'
export const APP_RESET = 'APP_RESET'
export const APP_BASE_URL = 'APP_BASE_URL'

// errors
export const GET_ERRORS = 'GET_ERRORS'
export const SET_ERRORS = 'SET_ERRORS'

// alerts
export const CLEAR_ALERTS = 'CLEAR_ALERTS'

// Catalogue Subscriptions
export const GET_CATALOG_SUBSCRIPTIONS_SUBMIT = 'GET_CATALOG_SUBSCRIPTIONS_SUBMIT'
export const GET_CATALOG_SUBSCRIPTIONS_SUCCESS = 'GET_CATALOG_SUBSCRIPTIONS_SUCCESS'
export const GET_CATALOG_SUBSCRIPTIONS_ERROR = 'GET_CATALOG_SUBSCRIPTIONS_ERROR'

export const UPDATE_CATALOG_SUBSCRIPTIONS_SUBMIT = 'UPDATE_CATALOG_SUBSCRIPTIONS_SUBMIT'
export const UPDATE_CATALOG_SUBSCRIPTIONS_SUCCESS = 'UPDATE_CATALOG_SUBSCRIPTIONS_SUCCESS'
export const UPDATE_CATALOG_SUBSCRIPTIONS_ERROR = 'UPDATE_CATALOG_SUBSCRIPTIONS_ERROR'

export const REORDER_DEPARTMENTS_SUBMIT = 'REORDER_DEPARTMENTS_SUBMIT'
export const REORDER_DEPARTMENTS_SUCCESS = 'REORDER_DEPARTMENTS_SUCCESS'
export const REORDER_DEPARTMENTS_ERROR = 'REORDER_DEPARTMENTS_ERROR'

export const EDIT_DEPARTMENT_LIST = 'EDIT_DEPARTMENT_LIST'
export const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT'
export const EDIT_CATALOGUE_LIST = 'EDIT_CATALOGUE_LIST'
export const EDIT_CATALOGUE = 'EDIT_CATALOGUE'

export const SET_SELECTED_DEPARTMENT = 'SET_SELECTED_DEPARTMENT'
export const CLEAR_SELECTED_DEPARTMENT = 'CLEAR_SELECTED_DEPARTMENT'

export const SET_SELECTED_CATALOGUE = 'SET_SELECTED_CATALOGUE'
export const CLEAR_SELECTED_CATALOGUE = 'CLEAR_SELECTED_CATALOGUE'
