// App state
export const APP_INIT = 'APP_INIT';
export const APP_RESET = 'APP_RESET';
export const APP_BASE_URL = 'APP_BASE_URL';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const SET_ERRORS = 'SET_ERRORS';

// alerts
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// Catalogue Subscriptions
export const GET_PRESS_RELEASES_SUBMIT = 'GET_PRESS_RELEASES_SUBMIT';
export const GET_PRESS_RELEASES_SUCCESS = 'GET_PRESS_RELEASES_SUCCESS';
export const GET_PRESS_RELEASES_ERROR = 'GET_PRESS_RELEASES_ERROR';

export const GET_PRESS_RELEASE_ARTICLE_SUBMIT = 'GET_PRESS_RELEASE_ARTICLE_SUBMIT';
export const GET_PRESS_RELEASE_ARTICLE_SUCCESS = 'GET_PRESS_RELEASE_ARTICLE_SUCCESS';
export const GET_PRESS_RELEASE_ARTICLE_ERROR = 'GET_PRESS_RELEASE_ARTICLE_ERROR';

export const UPDATE_PRESS_RELEASE_ARTICLE_SUBMIT = 'UPDATE_PRESS_RELEASE_ARTICLE_SUBMIT';
export const UPDATE_PRESS_RELEASE_ARTICLE_SUCCESS = 'UPDATE_PRESS_RELEASE_ARTICLE_SUCCESS';
export const UPDATE_PRESS_RELEASE_ARTICLE_ERROR = 'UPDATE_PRESS_RELEASE_ARTICLE_ERROR';

export const DELETE_PRESS_RELEASE_ARTICLE_SUBMIT = 'DELETE_PRESS_RELEASE_ARTICLE_SUBMIT';
export const DELETE_PRESS_RELEASE_ARTICLE_SUCCESS = 'DELETE_PRESS_RELEASE_ARTICLE_SUCCESS';
export const DELETE_PRESS_RELEASE_ARTICLE_ERROR = 'DELETE_PRESS_RELEASE_ARTICLE_ERROR';

export const UPLOAD_PRESS_RELEASE_PDF_SUBMIT = 'UPLOAD_PRESS_RELEASE_PDF_SUBMIT';
export const UPLOAD_PRESS_RELEASE_PDF_SUCCESS = 'UPLOAD_PRESS_RELEASE_PDF_SUCCESS';
export const UPLOAD_PRESS_RELEASE_PDF_ERROR = 'UPLOAD_PRESS_RELEASE_PDF_ERROR';

export const EDIT_PRESS_RELEASE = 'EDIT_PRESS_RELEASE';
export const EDIT_PRESS_RELEASE_LIST = 'EDIT_PRESS_RELEASE_LIST';

export const SET_SELECTED_PRESS_RELEASE = 'SET_SELECTED_PRESS_RELEASE';
export const CLEAR_SELECTED_PRESS_RELEASE = 'CLEAR_SELECTED_PRESS_RELEASE';

export const SET_DEPARTMENT_LIST = 'SET_DEPARTMENT_LIST';
export const SET_LOCATION_INFO = 'SET_LOCATION_INFO';
