// App state
export const APP_INIT = 'APP_INIT';
export const APP_RESET = 'APP_RESET';
export const APP_BASE_URL = 'APP_BASE_URL';
export const API_BASE_URL = 'API_BASE_URL';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const SET_ERRORS = 'SET_ERRORS';

// alerts
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// Editorials
export const BIDS_LOGIN_SUBMIT = 'BIDS_LOGIN_SUBMIT';
export const BIDS_LOGIN_SUCCESS = 'BIDS_LOGIN_SUCCESS';
export const BIDS_LOGIN_ERROR = 'BIDS_LOGIN_ERROR';

export const GET_USERS_SUBMIT = 'GET_USERS_SUBMIT';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const GET_USER_DETAILS_SUBMIT = 'GET_USER_DETAILS_SUBMIT';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';

export const UPDATE_USER_SUBMIT = 'UPDATE_USER_SUBMIT';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const GET_COUNTRIES_SUBMIT = 'GET_COUNTRIES_SUBMIT';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR';

export const GET_STATES_SUBMIT = 'GET_STATES_SUBMIT';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_ERROR = 'GET_STATES_ERROR';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_LIST = 'EDIT_USER_LIST';
export const EDIT_USER_DROPDOWNS = 'EDIT_USER_DROPDOWNS';
export const EDIT_USER_ADDRESS = 'EDIT_USER_ADDRESS';

export const SET_USER_QUERY_STRING = 'SET_USER_QUERY_STRING';
export const CLEAR_USER_QUERY_STRING = 'CLEAR_USER_QUERY_STRING';

export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const CLEAR_SELECTED_USER = 'CLEAR_SELECTED_USER';

export const SET_NEW_USER = 'SET_NEW_USER';
