// App state
export const APP_INIT = 'APP_INIT';
export const APP_RESET = 'APP_RESET';
export const APP_BASE_URL = 'APP_BASE_URL';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const SET_ERRORS = 'SET_ERRORS';

// alerts
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// Editorials
export const GET_EDITORIALS_SUBMIT = 'GET_EDITORIALS_SUBMIT';
export const GET_EDITORIALS_SUCCESS = 'GET_EDITORIALS_SUCCESS';
export const GET_EDITORIALS_ERROR = 'GET_EDITORIALS_ERROR';

export const UPDATE_EDITORIAL_SUBMIT = 'UPDATE_EDITORIAL_SUBMIT';
export const UPDATE_EDITORIAL_SUCCESS = 'UPDATE_EDITORIAL_SUCCESS';
export const UPDATE_EDITORIAL_ERROR = 'UPDATE_EDITORIAL_ERROR';

export const UPDATE_EDITORIAL_ARTICLES_SUBMIT = 'UPDATE_EDITORIAL_ARTICLES_SUBMIT';
export const UPDATE_EDITORIAL_ARTICLES_SUCCESS = 'UPDATE_EDITORIAL_ARTICLES_SUCCESS';
export const UPDATE_EDITORIAL_ARTICLES_ERROR = 'UPDATE_EDITORIAL_ARTICLES_ERROR';

export const DELETE_EDITORIAL_ARTICLE_SUBMIT = 'DELETE_EDITORIAL_ARTICLE_SUBMIT';
export const DELETE_EDITORIAL_ARTICLE_SUCCESS = 'DELETE_EDITORIAL_ARTICLE_SUCCESS';
export const DELETE_EDITORIAL_ARTICLE_ERROR = 'DELETE_EDITORIAL_ARTICLE_ERROR';

export const UPLOAD_EDITORIAL_IMAGE_SUBMIT = 'UPLOAD_EDITORIAL_IMAGE_SUBMIT';
export const UPLOAD_EDITORIAL_IMAGE_SUCCESS = 'UPLOAD_EDITORIAL_IMAGE_SUCCESS';
export const UPLOAD_EDITORIAL_IMAGE_ERROR = 'UPLOAD_EDITORIAL_IMAGE_ERROR';

export const EDITORIAL_UPLOAD_IMAGE_SET = 'EDITORIAL_UPLOAD_IMAGE_SET';
export const EDITORIAL_UPLOAD_IMAGE_CLEAR = 'EDITORIAL_UPLOAD_IMAGE_CLEAR';

export const EDIT_EDITORIAL = 'EDIT_EDITORIAL';
export const EDIT_COMPONENT = 'EDIT_COMPONENT';
export const EDIT_EDITORIAL_LIST = 'EDIT_EDITORIAL_LIST';
export const EDIT_EDITORIAL_COMPONENT_LIST = 'EDIT_EDITORIAL_COMPONENT_LIST';

export const SET_SELECTED_EDITORIAL = 'SET_SELECTED_EDITORIAL';
export const CLEAR_SELECTED_EDITORIAL = 'CLEAR_SELECTED_EDITORIAL';

export const SET_SELECTED_COMPONENT = 'SET_SELECTED_COMPONENT';
export const CLEAR_SELECTED_COMPONENT = 'CLEAR_SELECTED_COMPONENT';

export const SET_NEW_EDITORIAL_TYPE = 'SET_NEW_EDITORIAL_TYPE';
export const EDITORIAL_DROPPED = 'EDITORIAL_DROPPED';
