'use strict'

// App state
export const APP_INIT = 'APP_INIT'

export const CACHE_PURGE_SUBMIT = 'CACHE_PURGE_SUBMIT'
export const CACHE_PURGE_SUCCESS = 'CACHE_PURGE_SUCCESS'
export const CACHE_PURGE_ERROR = 'CACHE_PURGE_ERROR'

export const CLEAR_ALERTS = "CLEAR_ALERTS"

export const SET_SELECTED_CACHE_ENDPOINT = "SET_SELECTED_CACHE_ENDPOINT"