// App state
export const APP_INIT = 'APP_INIT';
export const APP_RESET = 'APP_RESET';
export const APP_BASE_URL = 'APP_BASE_URL';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const SET_ERRORS = 'SET_ERRORS';

// alerts
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// Auctions
export const AUCTIONS_REQUESTED = 'AUCTIONS_REQUESTED';
export const AUCTIONS_REQUEST_SUCCESS = 'AUCTIONS_REQUEST_SUCCESS';
export const AUCTIONS_REQUEST_ERROR = 'AUCTIONS_REQUEST_ERROR';

export const EDIT_AUCTIONS_DISPLAY_LIST = 'EDIT_AUCTIONS_DISPLAY_LIST';
export const AUCTION_SELECTED = 'AUCTION_SELECTED';

// Lots
export const AUCTION_LOTS_REQUESTED = 'AUCTION_LOTS_REQUESTED';
export const AUCTION_LOTS_REQUEST_SUCCESS = 'AUCTION_LOTS_REQUEST_SUCCESS';
export const AUCTION_LOTS_REQUEST_ERROR = 'AUCTION_LOTS_REQUEST_ERROR';

export const LOT_SELECTED = 'LOT_SELECTED';

// Lot Components
export const GET_LOT_COMPONENTS_SUBMIT = 'GET_LOT_COMPONENTS_SUBMIT';
export const GET_LOT_COMPONENTS_SUCCESS = 'GET_LOT_COMPONENTS_SUCCESS';
export const GET_LOT_COMPONENTS_ERROR = 'GET_LOT_COMPONENTS_ERROR';

export const UPDATE_LOT_COMPONENT_SUBMIT = 'UPDATE_LOT_COMPONENT_SUBMIT';
export const UPDATE_LOT_COMPONENT_SUCCESS = 'UPDATE_LOT_COMPONENT_SUCCESS';
export const UPDATE_LOT_COMPONENT_ERROR = 'UPDATE_LOT_COMPONENT_ERROR';

export const DELETE_LOT_COMPONENT_SUBMIT = 'DELETE_LOT_COMPONENT_SUBMIT';
export const DELETE_LOT_COMPONENT_SUCCESS = 'DELETE_LOT_COMPONENT_SUCCESS';
export const DELETE_LOT_COMPONENT_ERROR = 'DELETE_LOT_COMPONENT_ERROR';

export const UPLOAD_LOT_COMPONENT_IMAGE_SUBMIT = 'UPLOAD_LOT_COMPONENT_IMAGE_SUBMIT';
export const UPLOAD_LOT_COMPONENT_IMAGE_SUCCESS = 'UPLOAD_LOT_COMPONENT_IMAGE_SUCCESS';
export const UPLOAD_LOT_COMPONENT_IMAGE_ERROR = 'UPLOAD_LOT_COMPONENT_IMAGE_ERROR';

export const LOT_COMPONENT_UPLOAD_IMAGE_SET = 'LOT_COMPONENT_UPLOAD_IMAGE_SET';
export const LOT_COMPONENT_UPLOAD_IMAGE_CLEAR = 'LOT_COMPONENT_UPLOAD_IMAGE_CLEAR';

export const EDIT_LOT_COMPONENT = 'EDIT_LOT_COMPONENT';
export const EDIT_LOT_COMPONENTDATA = 'EDIT_LOT_COMPONENTDATA';
export const EDIT_LOT_COMPONENTDATA_IMAGE = 'EDIT_LOT_COMPONENTDATA_IMAGE';
export const EDIT_LOT_COMPONENT_LIST = 'EDIT_LOT_COMPONENT_LIST';

export const ADD_CAROUSEL_ITEM = 'ADD_CAROUSEL_ITEM';
export const DELETE_CAROUSEL_ITEM = 'DELETE_CAROUSEL_ITEM';

export const SET_SELECTED_LOT_COMPONENT = 'SET_SELECTED_LOT_COMPONENT';
export const SET_SELECTED_LOT_COMPONENT_DATA = 'SET_SELECTED_LOT_COMPONENT_DATA';
export const CLEAR_SELECTED_LOT_COMPONENT = 'CLEAR_SELECTED_LOT_COMPONENT';
export const CLEAR_SELECTED_LOT_COMPONENT_DATA = 'CLEAR_SELECTED_LOT_COMPONENT_DATA';

export const SET_NEW_LOT_COMPONENT_TYPE = 'SET_NEW_LOT_COMPONENT_TYPE';
export const LOT_COMPONENT_DROPPED = 'LOT_COMPONENT_DROPPED';

export const SET_PREVIOUSLY_SELECTED_COMPONENTID = 'SET_PREVIOUSLY_SELECTED_COMPONENTID';

export const SET_DEPARTMENT_LIST = 'SET_DEPARTMENT_LIST';
export const SET_LOCATION_INFO = 'SET_LOCATION_INFO';
