'use strict'

// App state
export const APP_INIT = 'APP_INIT'
export const APP_RESET = 'APP_RESET'
export const APP_BASE_URL = 'APP_BASE_URL'

// dialog
export const SHOW_DELETE_DIALOG = 'SHOW_DELETE_DIALOG'

// Sticky
export const STICKY_DELETE_CANCEL = 'STICKY_DELETE_CANCEL'
export const STICKY_DELETE_SUMBIT = 'STICKY_DELETE_SUMBIT'
export const STICKY_IMAGE_SUMBIT = 'STICKY_IMAGE_SUMBIT'
export const STICKY_IMAGE_SUCCESS = 'STICKY_IMAGE_SUCCESS'
export const STICKY_PROPERTY_CHANGED = 'STICKY_PROPERTY_CHANGED'
export const STICKY_REORDER_SUBMIT = 'STICKY_REORDER_SUBMIT'
export const STICKY_REORDER_SUCCESS = 'STICKY_REORDER_SUCCESS'
export const STICKY_REORDER_ERROR = 'STICKY_REORDER_ERROR'
export const STICKY_REQUEST = 'STICKY_REQUEST'
export const STICKY_REQUEST_SUCCESS = 'STICKY_REQUEST_SUCCESS'
export const STICKY_REQUEST_ERROR = 'STICKY_REQUEST_ERROR'
export const STICKY_SELECTED = 'STICKY_SELECTED'
export const STICKY_SHOW_NEW_FORM = 'STICKY_SHOW_NEW_FORM'
export const STICKY_UPDATE_SUMBIT = 'STICKY_UPDATE_SUMBIT'
export const STICKY_UPDATE_SUCCESS = 'STICKY_UPDATE_SUCCESS'

//errors
export const GET_ERRORS = 'GET_ERRORS'
export const SET_ERRORS = 'SET_ERRORS'

//alerts
export const CLEAR_ALERTS = 'CLEAR_ALERTS'
