// App state
export const APP_INIT = 'APP_INIT';
export const APP_RESET = 'APP_RESET';
export const APP_BASE_URL = 'APP_BASE_URL';

// errors
export const GET_ERRORS = 'GET_ERRORS';
export const SET_ERRORS = 'SET_ERRORS';

// alerts
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// Catalogue Subscriptions
export const GET_MAKER_BIOS_SUBMIT = 'GET_MAKER_BIOS_SUBMIT';
export const GET_MAKER_BIOS_SUCCESS = 'GET_MAKER_BIOS_SUCCESS';
export const GET_MAKER_BIOS_ERROR = 'GET_MAKER_BIOS_ERROR';

export const UPDATE_MAKER_BIO_SUBMIT = 'UPDATE_MAKER_BIO_SUBMIT';
export const UPDATE_MAKER_BIO_SUCCESS = 'UPDATE_MAKER_BIO_SUCCESS';
export const UPDATE_MAKER_BIO_ERROR = 'UPDATE_MAKER_BIO_ERROR';

// export const DELETE_MAKER_BIO_SUBMIT = 'DELETE_MAKER_BIO_SUBMIT';
// export const DELETE_MAKER_BIO_SUCCESS = 'DELETE_MAKER_BIO_SUCCESS';
// export const DELETE_MAKER_BIO_ERROR = 'DELETE_MAKER_BIO_ERROR';

export const EDIT_MAKER_BIO = 'EDIT_MAKER_BIO';
export const EDIT_MAKER_BIO_LIST = 'EDIT_MAKER_BIO_LIST';

export const SET_SELECTED_MAKER_BIO = 'SET_SELECTED_MAKER_BIO';
export const CLEAR_SELECTED_MAKER_BIO = 'CLEAR_SELECTED_MAKER_BIO';
