// App state
export const APP_INIT = 'APP_INIT';
export const APP_RESET = 'APP_RESET';
export const APP_BASE_URL = 'APP_BASE_URL';

// Auctions
export const AUCTIONS_REQUESTED = 'AUCTIONS_REQUESTED';
export const AUCTIONS_REQUEST_SUCCESS = 'AUCTIONS_REQUEST_SUCCESS';
export const AUCTIONS_REQUEST_ERROR = 'AUCTIONS_REQUEST_ERROR';

// Selected Auction
export const AUCTION_SELECTED = 'AUCTION_SELECTED';
export const LOAD_SELECTED_AUCTION_SUBMIT = 'LOAD_SELECTED_AUCTION_SUBMIT';
export const LOAD_SELECTED_AUCTION_ERROR = 'LOAD_SELECTED_AUCTION_ERROR';
export const LOAD_SELECTED_AUCTION_SUCCESS = 'LOAD_SELECTED_AUCTION_SUCCESS';

// Update Auctions
export const AUCTION_EDITED = 'AUCTION_EDITED';
export const UPDATE_AUCTION_SUCCESS = 'UPDATE_AUCTION_SUCCESS';
export const UPDATE_AUCTION_ERROR = 'UPDATE_AUCTION_ERROR';
export const UPDATE_AUCTION_SUBMIT = 'UPDATE_AUCTION_SUBMIT';
export const UPDATE_AUCTION_DIALOG_OPEN = 'UPDATE_AUCTION_DIALOG_OPEN';

// Auction Banner Upload
export const UPLOAD_AUCTION_BANNER_SUBMIT = 'UPLOAD_AUCTION_BANNER_SUBMIT';
export const UPLOAD_AUCTION_BANNER_ERROR = 'UPLOAD_AUCTION_BANNER_ERROR';
export const UPLOAD_AUCTION_BANNER_SUCCESS = 'UPLOAD_AUCTION_BANNER_SUCCESS';

// Details
export const EDIT_AUCTION_FIELD = 'EDIT_AUCTION_FIELD';

// Image uploads
export const SET_UPLOAD_IMAGE = 'SET_UPLOAD_IMAGE';
export const CLEAR_UPLOAD_IMAGE = 'CLEAR_UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';
export const UPLOAD_IMAGE_SUBMIT = 'UPLOAD_IMAGE_SUBMIT';

export const UPLOAD_IOSMOBILEBANNER_SUBMIT = 'UPLOAD_IOSMOBILEBANNER_SUBMIT';
export const UPLOAD_IOSMOBILEBANNER_ERROR = 'UPLOAD_IOSMOBILEBANNER_ERROR';
export const UPLOAD_IOSMOBILEBANNER_SUCCESS = 'UPLOAD_IOSMOBILEBANNER_SUCCESS';
export const UPLOAD_IOSDESKTOPBANNER_SUBMIT = 'UPLOAD_IOSDESKTOPBANNER_SUBMIT';
export const UPLOAD_IOSDESKTOPBANNER_ERROR = 'UPLOAD_IOSDESKTOPBANNER_ERROR';
export const UPLOAD_IOSDESKTOPBANNER_SUCCESS = 'UPLOAD_IOSDESKTOPBANNER_SUCCESS';
export const UPLOAD_CATALOG_COVER_SUBMIT = 'UPLOAD_CATALOG_COVER_SUBMIT';
export const UPLOAD_CATALOG_COVER_ERROR = 'UPLOAD_CATALOG_COVER_ERROR';
export const UPLOAD_CATALOG_COVER_SUCCESS = 'UPLOAD_CATALOG_COVER_SUCCESS';

// File uploads
export const UPLOAD_SALE_RESULTS_SUBMIT = 'UPLOAD_SALE_RESULTS_SUBMIT';
export const UPLOAD_SALE_RESULTS_ERROR = 'UPLOAD_SALE_RESULTS_ERROR';
export const UPLOAD_SALE_RESULTS_SUCCESS = 'UPLOAD_SALE_RESULTS_SUCCESS';
export const UPLOAD_WINNER_BID_EMAIL_SUBMIT = 'UPLOAD_WINNER_BID_EMAIL_SUBMIT';
export const UPLOAD_WINNER_BID_EMAIL_ERROR = 'UPLOAD_WINNER_BID_EMAIL_ERROR';
export const UPLOAD_WINNER_BID_EMAIL_SUCCESS = 'UPLOAD_WINNER_BID_EMAIL_SUCCESS';

// Thumbnail Update
export const THUMBNAIL_DIALOG_OPEN = 'THUMBNAIL_DIALOG_OPEN';
export const THUMBNAIL_UPDATE = 'THUMBNAIL_UPDATE';
export const THUMBNAIL_UPDATE_SUCCESS = 'THUMBNAIL_UPDATE_SUCCESS';
export const THUMBNAIL_UPDATE_ERROR = 'THUMBNAIL_UPDATE_ERROR';

// Cloudinary Upload
export const CLOUDINARY_DIALOG_OPEN = 'CLOUDINARY_DIALOG_OPEN';
export const CLOUDINARY_UPLOAD_TRIGGER = 'CLOUDINARY_UPLOAD_TRIGGER';
export const CLOUDINARY_UPLOAD_FINISHED = 'CLOUDINARY_UPLOAD_FINISHED';
export const CLOUDINARY_UPLOAD_ERROR = 'CLOUDINARY_UPLOAD_ERROR';

export const CLOUDINARY_GET_UPLOAD_STATUS = 'CLOUDINARY_GET_UPLOAD_STATUS';
export const CLOUDINARY_GET_UPLOAD_STATUS_SUCCESS = 'CLOUDINARY_GET_UPLOAD_STATUS_SUCCESS';
export const CLOUDINARY_GET_UPLOAD_STATUS_ERROR = 'CLOUDINARY_GET_UPLOAD_STATUS_ERROR';

// Alert Actions:
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

export const RESET_ALERT = 'RESET_ALERT';
export const UPDATE_AUCTION_SUCCESS_ALERT = 'UPDATE_AUCTION_SUCCESS_ALERT';
export const HIGHLIGHTS_SAVE_SUCCESS_ALERT = 'HIGHLIGHTS_SAVE_SUCCESS_ALERT';
export const HIGHLIGHTS_SAVE_ERROR_ALERT = 'HIGHLIGHTS_SAVE_ERROR_ALERT';
export const HIGHLIGHTS_DELETE_SUCCESS_ALERT = 'HIGHLIGHTS_DELETE_SUCCESS_ALERT';
export const HIGHLIGHTS_DELETE_ERROR_ALERT = 'HIGHLIGHTS_DELETE_ERROR_ALERT';
export const HIGHLIGHTS_IMAGE_UPLOAD_SUCCESS_ALERT = 'HIGHLIGHTS_IMAGE_UPLOAD_SUCCESS_ALERT';
export const HIGHLIGHTS_IMAGE_UPLOAD_ERROR_ALERT = 'HIGHLIGHTS_IMAGE_UPLOAD_ERROR_ALERT';
export const MIGRATE_PREVIEW_TO_STAGING_SUCCESS_ALERT = 'MIGRATE_PREVIEW_TO_STAGING_SUCCESS_ALERT';
export const HIGHLIGHTS_MIGRATE_FROM_PREVIEW_TO_PROD_SUCCESS_ALERT = 'HIGHLIGHTS_MIGRATE_FROM_PREVIEW_TO_PROD_SUCCESS_ALERT';

// Highlights Actions:
export const HIGHLIGHTS_GET_SUBMIT = 'HIGHLIGHTS_GET_SUBMIT';
export const HIGHLIGHTS_GET_SUCCESS = 'HIGHLIGHTS_GET_SUCCESS';
export const HIGHLIGHTS_GET_ERROR = 'HIGHLIGHTS_GET_ERROR';

export const HIGHLIGHTS_SAVE_SUBMIT = 'HIGHLIGHTS_SAVE_SUBMIT';
export const HIGHLIGHTS_SAVE_SUCCESS = 'HIGHLIGHTS_SAVE_SUCCESS';
export const HIGHLIGHTS_SAVE_ERROR = 'HIGHLIGHTS_SAVE_ERROR';

export const HIGHLIGHTS_DELETE_SUBMIT = 'HIGHLIGHTS_DELETE_SUBMIT';
export const HIGHLIGHTS_DELETE_SUCCESS = 'HIGHLIGHTS_DELETE_SUCCESS';
export const HIGHLIGHTS_DELETE_ERROR = 'HIGHLIGHTS_DELETE_ERROR';

export const HIGHLIGHTS_UPLOAD_IMAGE_SET = 'HIGHLIGHTS_UPLOAD_IMAGE_SET';
export const HIGHLIGHTS_UPLOAD_IMAGE_CLEAR = 'HIGHLIGHTS_UPLOAD_IMAGE_CLEAR';
export const HIGHLIGHTS_IMAGE_UPLOAD_SUBMIT = 'HIGHLIGHTS_IMAGE_UPLOAD_SUBMIT';
export const HIGHLIGHTS_IMAGE_UPLOAD_SUCCESS = 'HIGHLIGHTS_IMAGE_UPLOAD_SUCCESS';
export const HIGHLIGHTS_IMAGE_UPLOAD_ERROR = 'HIGHLIGHTS_IMAGE_UPLOAD_ERROR';

export const EDIT_HIGHLIGHTS_LIST = 'EDIT_HIGHLIGHTS_LIST';
export const EDIT_HIGHLIGHT = 'EDIT_HIGHLIGHT';

export const HIGHLIGHTS_SAVE_PROGRESS_LOCK = 'HIGHLIGHTS_SAVE_PROGRESS_LOCK';

export const SET_SELECTED_HIGHLIGHT = 'SET_SELECTED_HIGHLIGHT';
export const CLEAR_SELECTED_HIGHLIGHT = 'CLEAR_SELECTED_HIGHLIGHT';

export const HIGHLIGHTS_PUSH_TO_PROD_SUBMIT = 'HIGHLIGHTS_PUSH_TO_PROD_SUBMIT';
export const HIGHLIGHTS_PUSH_TO_PROD_SUCCESS = 'HIGHLIGHTS_PUSH_TO_PROD_SUCCESS';
export const HIGHLIGHTS_PUSH_TO_PROD_ERROR = 'HIGHLIGHTS_PUSH_TO_PROD_ERROR';
export const HIGHLIGHTS_PUSH_TO_PROD_DIALOG = 'HIGHLIGHTS_PUSH_TO_PROD_DIALOG';

export const HIGHLIGHTS_MIGRATE_FROM_PREVIEW_TO_PROD_SUBMIT = 'HIGHLIGHTS_MIGRATE_FROM_PREVIEW_TO_PROD_SUBMIT';
export const HIGHLIGHTS_MIGRATE_FROM_PREVIEW_TO_PROD_SUCCESS = 'HIGHLIGHTS_MIGRATE_FROM_PREVIEW_TO_PROD_SUCCESS';
export const HIGHLIGHTS_MIGRATE_FROM_PREVIEW_TO_PROD_ERROR = 'HIGHLIGHTS_MIGRATE_FROM_PREVIEW_TO_PROD_ERROR';
export const HIGHLIGHTS_MIGRATE_FROM_PREVIEW_TO_PROD_DIALOG = 'HIGHLIGHTS_MIGRATE_FROM_PREVIEW_TO_PROD_DIALOG';

// Lots
export const LOTS_GET_SUBMIT = 'LOTS_GET_SUBMIT';
export const LOTS_GET_SUCCESS = 'LOTS_GET_SUCCESS';
export const LOTS_GET_ERROR = 'LOTS_GET_ERROR';

// Lot
export const LOT_SELECTED = 'LOT_SELECTED';
export const EDIT_LOT_FIELD = 'EDIT_LOT_FIELD';
export const EDIT_LOT_IMAGES = 'EDIT_LOT_IMAGES';

// Update Lot
export const LOT_EDITED = 'LOT_EDITED';
export const UPDATE_LOT_SUCCESS = 'UPDATE_LOT_SUCCESS';
export const UPDATE_LOT_ERROR = 'UPDATE_LOT_ERROR';
export const UPDATE_LOT_SUBMIT = 'UPDATE_LOT_SUBMIT';
export const UPDATE_LOT_DIALOG_OPEN = 'UPDATE_LOT_DIALOG_OPEN';

// Lot Cloudinary Upload
export const CLOUDINARY_LOT_UPLOAD_SUBMIT = 'CLOUDINARY_LOT_UPLOAD_SUBMIT';
export const CLOUDINARY_LOT_UPLOAD_SUCCESS = 'CLOUDINARY_LOT_UPLOAD_SUCCESS';
export const CLOUDINARY_LOT_UPLOAD_ERROR = 'CLOUDINARY_LOT_UPLOAD_ERROR';

// Migrate preview to staging
export const MIGRATE_PREVIEW_TO_STAGING_SUBMIT = 'MIGRATE_PREVIEW_TO_STAGING_SUBMIT';
export const MIGRATE_PREVIEW_TO_STAGING_SUCCESS = 'MIGRATE_PREVIEW_TO_STAGING_SUCCESS';
export const MIGRATE_PREVIEW_TO_STAGING_DIALOG_OPEN = 'MIGRATE_PREVIEW_TO_STAGING_DIALOG_OPEN';
export const MIGRATE_PREVIEW_TO_STAGING_ERROR = 'MIGRATE_PREVIEW_TO_STAGING_ERROR';

// Lot Tags
export const TAGS_GET_SUBMIT = 'TAGS_GET_SUBMIT';
export const TAGS_GET_SUCCESS = 'TAGS_GET_SUCCESS';
export const TAGS_GET_ERROR = 'TAGS_GET_ERROR';

export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_ERROR = 'UPDATE_TAG_ERROR';
export const UPDATE_TAG_SUBMIT = 'UPDATE_TAG_SUBMIT';

export const EDIT_LOT_TAGS = 'EDIT_LOT_TAGS';

export const GET_WINNER_BID_EMAIL_STATUS_SUBMIT = 'GET_WINNER_BID_EMAIL_STATUS_SUBMIT';
export const GET_WINNER_BID_EMAIL_STATUS_ERROR = 'GET_WINNER_BID_EMAIL_STATUS_ERROR';
export const GET_WINNER_BID_EMAIL_STATUS_SUCCESS = 'GET_WINNER_BID_EMAIL_STATUS_SUCCESS';

// Departments:
export const SET_DEPARTMENT_LIST = 'SET_DEPARTMENT_LIST'

// Table List:
export const EDIT_AUCTIONS_DISPLAY_LIST = 'EDIT_AUCTIONS_DISPLAY_LIST';
export const EDIT_LOT_DISPLAY_LIST = 'EDIT_LOT_DISPLAY_LIST';

// Auction Mobility:
export const GET_AUCTION_MOBILITY_SALE_SUBMIT = 'GET_AUCTION_MOBILITY_SALE_SUBMIT';
export const GET_AUCTION_MOBILITY_SALE_SUCCESS = 'GET_AUCTION_MOBILITY_SALE_SUCCESS';
export const GET_AUCTION_MOBILITY_SALE_ERROR = 'GET_AUCTION_MOBILITY_SALE_ERROR';

export const UPDATE_AUCTION_MOBILITY_SALE_SUBMIT = 'UPDATE_AUCTION_MOBILITY_SALE_SUBMIT';
export const UPDATE_AUCTION_MOBILITY_SALE_SUCCESS = 'UPDATE_AUCTION_MOBILITY_SALE_SUCCESS';
export const UPDATE_AUCTION_MOBILITY_SALE_ERROR = 'UPDATE_AUCTION_MOBILITY_SALE_ERROR';
export const UPDATE_AUCTION_MOBILITY_SALE_BLOCKED = 'UPDATE_AUCTION_MOBILITY_SALE_BLOCKED';

export const UNLOCK_AUCTION_MOBILITY_SALE_SUBMIT = 'UNLOCK_AUCTION_MOBILITY_SALE_SUBMIT';
export const UNLOCK_AUCTION_MOBILITY_SALE_SUCCESS = 'UNLOCK_AUCTION_MOBILITY_SALE_SUCCESS';
export const UNLOCK_AUCTION_MOBILITY_SALE_ERROR = 'UNLOCK_AUCTION_MOBILITY_SALE_ERROR';
export const UNLOCK_AUCTION_MOBILITY_SALE_DIALOG = 'UNLOCK_AUCTION_MOBILITY_SALE_DIALOG';

export const EDIT_AM_DETAILS = 'EDIT_AM_DETAILS';

export const SET_AUCTION_MOBILITY_SALE = 'SET_AUCTION_MOBILITY_SALE';
export const CLEAR_AUCTION_MOBILITY_SALE = 'CLEAR_AUCTION_MOBILITY_SALE';
